FROM rust

ARG USER_ID
ARG GROUP_ID

RUN apt-get update

RUN apt-get install -y python3 curl && \
	curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
	python3 get-pip.py && \
	rm get-pip.py


RUN pip install maturin

RUN addgroup --gid $GROUP_ID builder
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID builder
USER builder
